[project]
name = "sumo-stgcn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.10.9",
    "pandas>=3.0.3",
    "pyproj>=3.7.2",
    "seaborn>=0.13.2",
    "sumolib>=1.27.0",
    "torch",
    "torch-geometric>=2.8.0",
    "tqdm>=4.68.1",
]

[project.optional-dependencies]
cpu = [
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
cuda = [
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]

[tool.uv]
conflicts = [
    [
        { extra = "cpu" },
        { extra = "cuda" },
    ],
]
environments = [
    "sys_platform == 'linux'",
    "sys_platform == 'win32'",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu128", extra = "cuda" },
]
torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu128", extra = "cuda" },
]
